language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1

matrix:
  fast_finish: true

notifications:
  email: false

addons:
  apt_packages:
    - gfortran
    - hdf5-tools

after_success:
  - julia -e 'import Pkg; cd(Pkg.dir("OcalAPI")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
